# Generated by Django 4.2 on 2024-02-26 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_errorlog"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="errorlog",
            name="user",
        ),
    ]
