# Generated by Django 4.2 on 2024-02-27 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_remove_errorlog_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="errorlog",
            options={"verbose_name": "Error Log", "verbose_name_plural": "Error Logs"},
        ),
    ]
