# Generated by Django 4.2 on 2024-02-28 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_alter_errorlog_created_at_profile_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usertestresult",
            name="score",
            field=models.PositiveIntegerField(),
        ),
    ]
